[package]
name = "ink_storage_derive"
version = "3.2.0"
authors = ["Parity Technologies <admin@parity.io>", "Robin Freyler <robin@parity.io>"]
edition = "2021"

license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/paritytech/ink"
documentation = "https://docs.rs/ink_storage_derive"
homepage = "https://www.parity.io/"
description = "[ink!] Derive macros for common ink_storage defined traits."
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "1", features = ["full"] }
proc-macro2 = "1"
synstructure = "0.12.6"
ink_storage_codegen = { version = "3.2.0", path = "../codegen" }

[dev-dependencies]
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive", "full"] }
ink_env = { version = "3.2.0", path = "../../env" }
ink_primitives = { version = "3.2.0", path = "../../primitives" }
ink_metadata = { version = "3.2.0", path = "../../metadata" }
ink_prelude = { version = "3.2.0", path = "../../prelude/" }
ink_storage = { version = "3.2.0", path = ".." }
