[package]
name = "incrementer"
version = "5.0.0-alpha"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
publish = false

[dependencies]
ink = { path = "../../../crates/ink", default-features = false }

migration = { path = "./migration", default-features = false, features = ["ink-as-dependency"] }
updated-incrementer = { path = "./updated-incrementer", default-features = false, features = ["ink-as-dependency"] }

[dev-dependencies]
ink_e2e = { path = "../../../crates/e2e" }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "migration/std",
    "updated-incrementer/std",
]
ink-as-dependency = []
e2e-tests = []
