[package]
name = "ink_storage_codegen"
version = "3.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/paritytech/ink"
documentation = "https://docs.rs/ink_storage_derive"
homepage = "https://www.parity.io/"
description = "[ink!] Utils codegen crate related to ink_storage."
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
ink_primitives = { version = "3.1.0", path = "../../primitives", default-features = false }
syn = { version = "1", features = ["full"] }