[workspace]
members = [
    "crates/metadata",
    "crates/allocator",
    "crates/lang",
    "crates/lang/macro",
    "crates/lang/ir",
    "crates/lang/codegen",
    "crates/prelude",
    "crates/primitives",
    "crates/env",
    "crates/storage",
    "crates/storage/derive",
]
exclude = [
    "examples/",
]

[profile.release]
panic = "abort"
lto = true
