[workspace]
members = [
    "metadata",
    "alloc",
    "core",
    "core/derive",
    "lang",
    "lang/macro",
    "lang/ir",
    "prelude",
    "primitives",
]
exclude = [
    "examples/",
]

[profile.release]
panic = "abort"
lto = true
