[package]
name = "ink_codegen"
version.workspace = true
authors = ["Use Ink <ink@use.ink>"]
edition.workspace = true

license.workspace = true
readme = "README.md"
repository.workspace = true
documentation = "https://docs.rs/ink_codegen/"
homepage.workspace = true
description = "data structures and algorithms for generating ink! IR code"
keywords.workspace = true
categories.workspace = true
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[lib]

[dependencies]
ink_primitives = { workspace = true }
ir = { version = "=6.0.0-alpha.4", package = "ink_ir", path = "../ir", default-features = false }
quote = { workspace = true }
syn = { workspace = true, features = ["parsing", "full", "extra-traits"] }
proc-macro2 = { workspace = true }
derive_more = { workspace = true, features = ["from"] }
itertools = { workspace = true }
either = { workspace = true }
blake2 = { workspace = true }
heck = { workspace = true }
scale = { workspace = true }
impl-serde = { workspace = true, default-features = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

polkavm-derive = { workspace = true }

[features]
default = [ "std" ]
std = [
    "either/std",
    "either/use_std",
    "ink_primitives/std",
    "ir/std",
    "itertools/use_std",
    "scale/std",
    "serde/std",
    "derive_more/std"
]

# For the ui tests, which use this `Cargo.toml`
[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    'cfg(feature, values(any()))',
    'cfg(ink_abi, values("ink", "sol", "all"))'
]
