[package]
name = "ink_codegen"
version.workspace = true
authors = ["Parity Technologies <admin@parity.io>", "Robin Freyler <robin@parity.io>"]
edition.workspace = true

license.workspace = true
readme = "README.md"
repository.workspace = true
documentation = "https://docs.rs/ink_codegen/"
homepage.workspace = true
description = "data structures and algorithms for generating ink! IR code"
keywords.workspace = true
categories.workspace = true
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[lib]
name = "ink_codegen"

[dependencies]
ink_primitives = { version = "=4.2.0", path = "../../primitives" }
ir = { version = "=4.2.0", package = "ink_ir", path = "../ir", default-features = false }
quote = "1"
syn = { version = "2.0", features = ["parsing", "full", "extra-traits"] }
proc-macro2 = "1.0"
derive_more = { version = "0.99", default-features = false, features = ["from"] }
itertools = "0.11"
either = { version = "1.5", default-features = false }
blake2 = "0.10"
heck = "0.4.0"
scale = { package = "parity-scale-codec", version = "3.4", default-features = false, features = ["derive"] }
impl-serde = "0.4.0"

serde = { version = "1.0.137", default-features = false, features = ["derive"] }
serde_json = "1.0.81"

[features]
default = ["std"]
std = [
    "itertools/use_std",
    "either/use_std",
    "ir/std"
]
