[package]
name = "call_builder"
version = "5.0.0-rc"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
publish = false

[dependencies]
ink = { path = "../../../crates/ink", default-features = false }

constructors_return_value = { path = "../constructors-return-value", default-features = false, features = ["ink-as-dependency"] }
integration_flipper = { path = "../integration-flipper", default-features = false, features = ["ink-as-dependency"] }

[dev-dependencies]
ink_e2e = { path = "../../../crates/e2e" }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",

    "constructors_return_value/std",
    "integration_flipper/std",
]
ink-as-dependency = []
e2e-tests = []
