[package]
name = "ink_macro"
version.workspace = true
authors = ["Parity Technologies <admin@parity.io>", "Robin Freyler <robin@parity.io>"]
edition.workspace = true

license.workspace = true
readme = "README.md"
repository.workspace = true
documentation = "https://docs.rs/ink_macro/"
homepage.workspace = true
description = "[ink!] Rust based eDSL for writing smart contracts for Substrate"
keywords.workspace = true
categories.workspace = true
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
ink_ir = { workspace = true }
ink_codegen = { workspace = true }
ink_primitives = { workspace = true }

scale = { package = "parity-scale-codec", workspace = true }
syn = { workspace = true }
synstructure = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }

[dev-dependencies]
ink_env = { workspace = true, default-features = true }
ink = { path = "..", default-features = true }
ink_metadata = { workspace = true, default-features = true }
ink_prelude = { workspace = true, default-features = true }
ink_storage = { workspace = true, default-features = true }
scale-info = { workspace = true, features = ["derive"] }

[lib]
name = "ink_macro"
proc-macro = true

[features]
default = ["std"]
std = [
    "scale/std",
    "ink_ir/std",
    "ink_primitives/std",
    "ink_codegen/std",
]
