[package]
name = "ink_macro"
version.workspace = true
authors = ["Use Ink <ink@use.ink>"]
edition.workspace = true

license.workspace = true
readme = "README.md"
repository.workspace = true
documentation = "https://docs.rs/ink_macro/"
homepage.workspace = true
description = "[ink!] Rust based eDSL for writing smart contracts for Substrate"
keywords.workspace = true
categories.workspace = true
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
ink_ir = { workspace = true }
ink_codegen = { workspace = true }
ink_primitives = { workspace = true }

scale = { workspace = true }
syn = { workspace = true }
synstructure = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }

[dev-dependencies]
ink_env = { workspace = true, default-features = true }
ink = { path = "..", default-features = true }
ink_metadata = { workspace = true, default-features = true }
ink_prelude = { workspace = true, default-features = true }
ink_storage = { workspace = true, default-features = true }
scale-info = { workspace = true, features = ["derive"] }

[lib]
proc-macro = true

[features]
default = ["std"]
std = [
    "ink_codegen/std",
    "ink_metadata/std",
    "ink_ir/std",
    "ink_primitives/std",
    "scale/std",
    "scale-info/std",
]

unstable-hostfn = ["ink_env/unstable-hostfn"]

# For the ui tests, which use this `Cargo.toml`
[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    'cfg(feature, values(any()))',
    'cfg(ink_abi, values("ink", "sol", "all"))'
]
