[package]
name = "ink_sandbox"
version = "6.0.0-alpha.4"
authors = ["Use Ink <ink@use.ink>", "Cardinal Cryptography"]
edition.workspace = true
license.workspace = true
description = "Sandbox runtime environment for ink! e2e tests"
repository.workspace = true
documentation = "https://docs.rs/ink_sandbox"
homepage.workspace = true

[dependencies]
sha3 = "0.10.8"
frame-metadata = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-balances = { workspace = true }
pallet-revive = { workspace = true }
pallet-timestamp = { workspace = true }
scale = { workspace = true }
sp-core = { workspace = true }
sp-externalities = { workspace = true }
sp-runtime = { workspace = true }
sp-io = { workspace = true }
ink_primitives = { workspace = true }

paste = { workspace = true }
scale-info = { workspace = true }

[features]
default = [
    # This is required for the runtime-interface to work properly in the std env.
    "std",
]
std = [
	"frame-support/std",
	"frame-system/std",
	"frame-metadata/std",
	"ink_primitives/std",
	"pallet-balances/std",
	"pallet-revive/std",
	"pallet-timestamp/std",
	"scale/std",
	"scale-info/std",
	"sp-core/std",
	"sp-externalities/std",
	"sp-io/std"
]
