[package]
name = "ink_lang_macro"
version = "3.0.0-rc5"
authors = ["Parity Technologies <admin@parity.io>", "Robin Freyler <robin@parity.io>"]
edition = "2018"

license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/paritytech/ink"
documentation = "https://docs.rs/ink_lang_macro/"
homepage = "https://www.parity.io/"
description = "[ink!] Rust based eDSL for writing smart contracts for Substrate"
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
ink_lang_ir = { version = "3.0.0-rc5", path = "../ir", default-features = false }
ink_lang_codegen = { version = "3.0.0-rc5", path = "../codegen", default-features = false }
ink_primitives = { version = "3.0.0-rc5", path = "../../primitives/", default-features = false }

scale = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive"] }
syn = "1"
proc-macro2 = "1"

[dev-dependencies]
ink_metadata = { version = "3.0.0-rc5", path = "../../metadata/" }
ink_env = { version = "3.0.0-rc5", path = "../../env/" }
ink_storage = { version = "3.0.0-rc5", path = "../../storage/" }
ink_lang = { version = "3.0.0-rc5", path = ".." }
ink_prelude = { version = "3.0.0-rc5", path = "../../prelude/" }

trybuild = "1"
scale-info = { version = "0.6", default-features = false, features = ["derive"] }

[lib]
name = "ink_lang_macro"
proc-macro = true

[features]
default = ["std"]
std = [
    "scale/std",
    "ink_lang_ir/std",
    "ink_primitives/std",
]

# Due to https://github.com/rust-lang/cargo/issues/6915 features that affect a dev-dependency
# currently can't be enabled by a parent crate, hence `["ink_env/ink-experimental-engine"]` does
# not work.
# After we switch to the new off-chain environment with https://github.com/paritytech/ink/issues/565
# we can remove the feature altogether.
ink-experimental-engine = []
