# This file corresponds to the `rust-toolchain` file used for the `dylint` examples here:
# https://github.com/trailofbits/dylint/blob/master/internal/template/rust-toolchain

[toolchain]
channel = "nightly-2025-05-14"
components = ["llvm-tools-preview", "rustc-dev"]
