[package]
name = "sandbox-runtime"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ink_sandbox = { path = "../../../../crates/e2e/sandbox" }
pallet-contract-caller = { path = "pallet-contract-caller", default-features = false }
frame-support = { workspace = true }
frame-system = { workspace = true }
codec = { workspace = true }
scale-info = { workspace = true }

[features]
default = ["std"]
std = [
    "pallet-contract-caller/std",
]
