[package]
name = "ink_primitives"
version.workspace = true
authors = ["Use Ink <ink@use.ink>"]
edition.workspace = true

license.workspace = true
readme = "README.md"
repository.workspace = true
documentation = "https://docs.rs/ink_primitives/"
homepage.workspace = true
description = "[ink!] Fundamental primitive types for ink! smart contracts."
keywords.workspace = true
categories.workspace = true
include = ["/Cargo.toml", "src/**/*.rs", "/README.md", "/LICENSE"]

[dependencies]
alloy-sol-types = { workspace = true }
derive_more = { workspace = true, features = ["from", "display"] }
ink_prelude = { workspace = true }
scale = { workspace = true, features = ["max-encoded-len"] }
scale-decode = { workspace = true, features = ["derive"] }
scale-encode = { workspace = true, features = ["derive"], optional = true }
pallet-revive-uapi = { workspace = true }
paste = { workspace = true }
primitive-types = { version = "0.13.1", default-features = false, features = ["codec"] }
scale-info = { workspace = true, features = ["derive"], optional = true }
xxhash-rust = { workspace = true, features = ["const_xxh32"] }
serde = { version = "1.0.215", features = ["derive"], default-features = false, optional = true }
cfg-if = { workspace = true }
num-traits = { workspace = true, features = ["i128"] }
sp-core = { workspace = true }

sp-io = { git = "https://github.com/use-ink/polkadot-sdk.git", rev = "a71ec19a94702ea71767ba5ac97603ea6c6305c1", default-features = false, features = ["disable_panic_handler", "disable_oom", "disable_allocator"] }
sp-runtime-interface = { git = "https://github.com/use-ink/polkadot-sdk.git", rev = "a71ec19a94702ea71767ba5ac97603ea6c6305c1", default-features = false, features = ["disable_target_static_assertions"] }
sp-weights = { workspace = true }
impl-trait-for-tuples = { workspace = true }
itertools = { workspace = true }

[dev-dependencies]
ink = { workspace = true, default-features = false }
ink_env = { workspace = true, default-features = false }

[features]
default = ["std"]
std = [
    "alloy-sol-types/std",
    "ink/std",
    "ink_env/std",
    "ink_prelude/std",
    "num-traits/std",
    "serde",
    "serde/std",
    "scale-encode",
    "scale-info/std",
    "scale/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime-interface/std",
    "sp-weights/std",
    "primitive-types/std",
    "primitive-types/scale-info",
    "derive_more/std",
    "xxhash-rust/std"
]
