[package]
name = "instantiate_contract"
version = "0.1.0"
edition = "2021"
authors = ["VÃ­ctor M. GonzÃ¡lez <victor.gonzalez@coinfabrik.com>"]

[lib]
path = "lib.rs"

[features]
default = ["std", "test_instantiate"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
    "contract1/std",
    "contract2/std",
    "virtual_contract/std",
    "virtual_contract_ver1/std",
    "virtual_contract_ver2/std",
]
ink-as-dependency = []
e2e-tests = []
test_instantiate = [
    "ink/test_instantiate",
    "contract1/test_instantiate",
    "contract2/test_instantiate",
    "virtual_contract/test_instantiate",
    "virtual_contract_ver1/test_instantiate",
    "virtual_contract_ver2/test_instantiate",
]

[dependencies]
ink = { path = "../../crates/ink", default-features = false }
scale = { package = "parity-scale-codec", version = "=3.6.5", default-features = false, features = [
    "derive",
] }
scale-info = { version = "2.6", default-features = false, features = [
    "derive",
], optional = true }
contract1 = { path = "./contract1", default-features = false, features = [
    "ink-as-dependency",
] }
contract2 = { path = "./contract2", default-features = false, features = [
    "ink-as-dependency",
] }
virtual_contract = { path = "./virtual_contract", default-features = false, features = [
    "ink-as-dependency",
] }
virtual_contract_ver1 = { path = "./virtual_contract_ver1", default-features = false, features = [
    "ink-as-dependency",
] }
virtual_contract_ver2 = { path = "./virtual_contract_ver2", default-features = false, features = [
    "ink-as-dependency",
] }

[dev-dependencies]
ink_e2e = { path = "../../crates/e2e" }

[profile.dev]
overflow-checks = false

[profile.release]
overflow-checks = false
