[package]
name = "ink_metadata"
version = "3.0.0-rc2"
authors = ["Parity Technologies <admin@parity.io>", "Robin Freyler <robin@parity.io>"]
edition = "2018"

license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/paritytech/ink"
documentation = "https://docs.rs/ink_metadata/"
homepage = "https://www.parity.io/"
description = "[ink!] Metadata definitions for ink! smart contracts."
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
ink_prelude = { version = "3.0.0-rc2", path = "../prelude/", default-features = false }
ink_primitives = { version = "3.0.0-rc2", path = "../primitives/", default-features = false }

serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
impl-serde = "0.3.1"
derive_more = { version = "0.99", default-features = false, features = ["from"] }
scale-info = { version = "0.6", default-features = false, features = ["derive", "serde"] }

[dev-dependencies]
pretty_assertions = "0.6.1"
serde_json = "1.0"

[features]
default = [
    "std",
    "derive",
]
std = [
    "ink_prelude/std",
    "serde/std",
    "scale-info/std",
]
derive = []
