[package]
name = "invoke_contract"
version = "4.3.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
publish = false

[dependencies]
ink = { path = "../../crates/ink", default-features = false }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.5", default-features = false, features = ["derive"], optional = true }
contract_to_call = { path = "./contract_to_call", default-features = false, features = ["ink-as-dependency"] }

[dev-dependencies]
ink_e2e = { path = "../../crates/e2e" }

[lib]
path = "lib.rs"

[features]
default = ["std", "test_instantiate"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std"
]
test_instantiate = ["ink/test_instantiate", "contract_to_call/test_instantiate"]
ink-as-dependency = []
e2e-tests = []