[package]
name = "ink_linting_utils"
version.workspace = true
authors.workspace = true
edition.workspace = true

license.workspace = true
readme = "README.md"
repository.workspace = true
documentation = "https://docs.rs/ink_linting_utils"
homepage.workspace = true
description = "Utilities used internally in ink_linting"
keywords.workspace = true
include = ["Cargo.toml", "*.rs", "LICENSE"]

[dependencies]
if_chain = "1.0.2"

# The following `rev` is taken from the examples of the
# dylint version that we use:
# https://github.com/trailofbits/dylint/blob/v5.0.0/examples/supplementary/Cargo.toml#L44
ink_clippy_utils = { package = "clippy_utils", git = "https://github.com/rust-lang/rust-clippy", rev = "20ce69b9a63bcd2756cd906fe0964d1e901e042a" }

[package.metadata.rust-analyzer]
rustc_private = true
