[package]
name = "multi-contract-caller"
version = "6.0.0-alpha.4"
authors = ["Use Ink <ink@use.ink>"]
edition = "2024"
publish = false

[dependencies]
ink = { path = "../../../crates/ink", default-features = false }

adder = { path = "adder", default-features = false, features = ["ink-as-dependency"] }
subber = { path = "subber", default-features = false, features = ["ink-as-dependency"] }
accumulator = { path = "accumulator", default-features = false, features = ["ink-as-dependency"] }

[dev-dependencies]
ink_e2e = { path = "../../../crates/e2e" }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "adder/std",
    "subber/std",
    "accumulator/std",
]
ink-as-dependency = []
e2e-tests = []

[workspace]
members = [
    "accumulator",
    "adder",
    "subber",
]

[package.metadata.ink-lang]
abi = "ink"
