[package]
name = "abi-gen"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
publish = false

[[bin]]
name = "abi-gen"
path = "main.rs"

[dependencies]
contract = { path = "../..", package = "flipper", features = ["ink-generate-abi"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
