[package]
name = "tools"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
publish = false

[[bin]]
name = "abi_gen"
path = "abi-gen/main.rs"
doc = false

[dependencies]
contract = { path = "..", feature = ["generate-abi"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
