[package]
name = "erc20"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
ink_core = { git = "https://github.com/paritytech/ink/", package = "ink_core" }
ink_model = { git = "https://github.com/paritytech/ink/", package = "ink_model" }
ink_lang = { git = "https://github.com/paritytech/ink/", package = "ink_lang" }
# NOTE: because of this dependency (which depends on ink_core) the above ink dependencies need to be the same
# version, hence pointing at git rather than locally
ink_types_node_runtime = { git = "https://github.com/paritytech/ink-types-node-runtime", branch = "aj-mirror-types" }
parity-codec = { version = "3.2", default-features = false, features = ["derive"] }

[lib]
name = "erc20"
crate-type = ["cdylib"]

[features]
default = [
    "ink_lang/generate-api-description"
]
test-env = [
	"ink_core/test-env",
	"ink_model/test-env",
    "ink_lang/test-env",
]
generate-api-description = [
    "ink_lang/generate-api-description"
]

[profile.release]
panic = "abort"
lto = true
# debug = true
opt-level = "z"
