[package]
name = "custom-runtime"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ink_runtime = { path = "../../../../crates/runtime" }
pallet-revive-caller = { path = "pallet-revive-caller", default-features = false }
frame-support = { workspace = true }
frame-system = { workspace = true }
codec = { workspace = true }
scale-info = { workspace = true }

[features]
default = ["std"]
std = [
    "pallet-revive-caller/std",
]

[package.metadata.ink-lang]
abi = "ink"
