[package]
name = "flipper"
version = "5.0.0"
authors = ["Use Ink <ink@use.ink>"]
edition = "2021"
publish = false

[dependencies]
ink = { path = "../../../crates/ink", default-features = false }
polkavm-derive = "0.17.1"

[dev-dependencies]
ink_e2e = { path = "../../../crates/e2e" }
hex = { version = "0.4.3" }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
]
ink-as-dependency = []
e2e-tests = []
revive = ["ink/revive", "ink_e2e/revive"]
