[package]
name = "sol-cross-contract"
version = "6.0.0-alpha.4"
authors = ["Use Ink <ink@use.ink>"]
edition = "2024"
publish = false

[dependencies]
ink = { git = "https://github.com/use-ink/ink", tag = "v6.0.0-alpha.4", default-features = false }
sha3 = { version = "0.10", default-features = false }

[dev-dependencies]
ink_e2e = { git = "https://github.com/use-ink/ink", tag = "v6.0.0-alpha.4" }
ink_sandbox = { path = "../../../crates/sandbox" }
ink_revive_types = { path = "../../../crates/revive-types" }
sha3 = { version = "0.10" }
other-contract-sol = { path = "other-contract-sol" }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "sha3/std"
]
ink-as-dependency = []
e2e-tests = []

[package.metadata.ink-lang]
abi = "sol"
