[package]
name = "sol-cross-contract"
version = "6.0.0-alpha"
authors = ["Use Ink <ink@use.ink>"]
edition = "2021"
publish = false

[dependencies]
ink = { path = "../../../crates/ink", default-features = false }
sha3 = { version = "0.10", default-features = false }

[dev-dependencies]
ink_e2e = { path = "../../../crates/e2e", features = ["sandbox"] }
ink_sandbox = { path = "../../../crates/e2e/sandbox" }
pallet-revive = { git = "https://github.com/paritytech/polkadot-sdk.git", rev = "cb629d46ebf00aa65624013a61f9c69ebf02b0b4", default-features = false }
sha3 = { version = "0.10" }
other-contract-sol = { path = "other-contract-sol" }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "sha3/std"
]
ink-as-dependency = []
e2e-tests = []

[package.metadata.ink-lang]
abi = "sol"
