[package]
name = "adder"
version = "2.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
ink_primitives = { version = "2.1.0", path = "../../../primitives", default-features = false }
ink_abi = { version = "2.1.0", path = "../../../abi", default-features = false, features = ["derive"], optional = true }
ink_core = { version = "2.1.0", path = "../../../core", default-features = false }
ink_lang = { version = "2.1.0", path = "../../../lang", default-features = false }

accumulator = { version = "2.1.0", path = "../accumulator", default-features = false, features = ["ink-as-dependency"] }

scale = { package = "parity-scale-codec", version = "1.2", default-features = false, features = ["derive"] }

[dependencies.type-metadata]
git = "https://github.com/type-metadata/type-metadata.git"
rev = "02eae9f35c40c943b56af5b60616219f2b72b47d"
default-features = false
features = ["derive"]
optional = true


[lib]
name = "adder"
path = "lib.rs"
crate-type = [
	# Used for normal contract Wasm blobs.
	"cdylib",
	# Used for ABI generation.
	"rlib",
]

[features]
default = ["test-env"]
std = [
    "ink_primitives/std",
    "ink_abi/std",
    "ink_core/std",
    "ink_lang/std",
    "scale/std",
    "type-metadata/std",

    "accumulator/std",
]
test-env = [
	"std",
    "ink_lang/test-env",
]
ink-generate-abi = [
    "std",
    "ink_abi",
    "type-metadata",
    "ink_core/ink-generate-abi",
    "ink_lang/ink-generate-abi",

    "accumulator/ink-generate-abi",
]
ink-as-dependency = []
