[package]
name = "ink_e2e"
version = "4.0.0-alpha.3"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/paritytech/ink"
documentation = "https://docs.rs/ink_e2e/"
homepage = "https://www.parity.io/"
description = "[ink!] End-to-end testing framework for smart contracts."
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]
include = ["/Cargo.toml", "src/**/*.rs", "/README.md", "/LICENSE"]

[dependencies]
ink_e2e_macro = { version = "4.0.0-alpha.3", path = "./macro" }
ink_env = { version = "4.0.0-alpha.3", path = "../env" }

contract-metadata = { version = "2.0.0-alpha.2" }
impl-serde = { version = "0.3.1", default-features = false }
jsonrpsee = { version = "0.15.1", features = ["ws-client"] }
pallet-contracts-primitives = { version = "6.0.0" }
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.81" }
tokio = { version = "1.18.2", features = ["rt-multi-thread"] }
log = { version = "0.4" }
env_logger = { version = "0.9" }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive", "full"] }
subxt = { version = "0.24.0" }

# Substrate
sp-rpc = { version = "6.0.0" }
sp-core = { version = "6.0.0" }
sp-keyring = { version = "6.0.0" }
sp-runtime = { version = "6.0.0" }

# TODO(#1421) `smart-bench_macro` needs to be forked.
smart-bench-macro = { git = "https://github.com/paritytech/smart-bench", branch = "cmichi-ink-e2e-test-mvp", package = "smart-bench-macro" }

[features]
default = ["std"]
std = []
