# This file corresponds to the `rust-toolchain` file used for the `dylint` examples here:
# https://github.com/trailofbits/dylint/blob/ef7210cb08aac920c18d2141604efe210029f2a2/internal/template/rust-toolchain

[toolchain]
channel = "nightly-2023-07-14"
components = ["llvm-tools-preview", "rustc-dev"]
