[package]
name = "ink_lang"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

license = "MIT/Apache-2.0"
readme = "README.md"

# repository = "https://github.com/robbepop/substrate-contract"
# homepage = "https://github.com/robbepop/substrate-contract"
# documentation = "https://robbepop.github.io/pwasm-abi/substrate-contract/"

description = "[ink!] Rust based eDSL for writing smart contracts for Substrate"
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]

include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
ink_utils = { path = "../utils/" }
ink_model = { path = "../model/" }
parity-codec = { version = "3.2", default-features = false, features = ["derive"] }

quote = "0.6"
syn = { version = "0.15", features = ["parsing", "full", "extra-traits"] }
proc-macro2 = "0.4"
heck = "0.3"
itertools = "0.7"
either = "1.5"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"

[dev-dependencies]
pretty_assertions = "0.6.1"

[lib]
name = "ink_lang"
proc-macro = true

[features]
default = []
std = [
    "ink_utils/std",
    "parity-codec/std",
]
test-env = [
    "ink_model/test-env",
]
generate-api-description = []
