[package]
name = "ink_engine"
version = "4.0.0"
authors = ["Parity Technologies <admin@parity.io>", "Michael MÃ¼ller <michi@parity.io>"]
edition = "2021"

license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/paritytech/ink"
documentation = "https://docs.rs/ink_engine/"
homepage = "https://www.parity.io/"
description = "[ink!] Off-chain environment for testing."
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive", "full"] }
derive_more = { version = "0.99", default-features = false, features = ["from", "display"] }

sha2 = { version = "0.10" }
sha3 = { version = "0.10" }
blake2 = { version = "0.10" }

rand = { version = "0.8" }

# ECDSA for the off-chain environment.
secp256k1 = { version = "0.24.0", features = ["recovery", "global-context"], optional = true }

[features]
default = ["std"]
std = [
    "scale/std",
    "secp256k1"
]
