[package]
name = "ink_allocator"
version = "3.0.0-rc3"
authors = ["Parity Technologies <admin@parity.io>", "Robin Freyler <robin@parity.io>"]
edition = "2018"

license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/paritytech/ink"
documentation = "https://docs.rs/ink_allocator/"
homepage = "https://www.parity.io/"
description = "[ink!] Bindings to the Wasm heap memory allocator."
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
wee_alloc = { version = "0.4", default-features = false }

[features]
default = ["std"]
std = []
