[package]
name = "abi-gen"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
publish = false

[[bin]]
name = "abi-gen"
path = "main.rs"

[dependencies]
contract = { path = "../..", package = "multisig_plain" }
ink_lang = { path = "../../../../lang", package = "ink_lang" }
serde = "1.0"
serde_json = "1.0"
