[package]
name = "subber"
version = "3.3.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
ink_primitives = { path = "../../../crates/primitives", default-features = false }
ink_metadata = { path = "../../../crates/metadata", default-features = false, features = ["derive"], optional = true }
ink_env = { path = "../../../crates/env", default-features = false }
ink_storage = { path = "../../../crates/storage", default-features = false }
ink_lang = { path = "../../../crates/lang", default-features = false }

accumulator = { path = "../accumulator", default-features = false, features = ["ink-as-dependency"] }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }

[lib]
name = "subber"
path = "lib.rs"
crate-type = [
    # Used for normal contract Wasm blobs.
    "cdylib",
    # Used for ABI generation.
    "rlib",
]

[features]
default = ["std"]
std = [
    "ink_primitives/std",
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_lang/std",
    "scale/std",
    "scale-info/std",

    "accumulator/std",
]
ink-as-dependency = []
