[package]
name = "subber"
version = "4.2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
ink = { path = "../../../crates/ink", default-features = false }

accumulator = { path = "../accumulator", default-features = false, features = ["ink-as-dependency"] }

parity-scale-codec-derive = { version = "=3.1.4", default-features = false, optional = true }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.6", default-features = false, features = ["derive"], optional = true }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",

    "accumulator/std",
]
ink-as-dependency = []
