[package]
name = "ink_e2e_macro"
version.workspace = true
authors.workspace = true
edition.workspace = true

license.workspace = true
readme = "../README.md"
repository.workspace = true
documentation = "https://docs.rs/ink_macro/"
homepage.workspace = true
description = "[ink!] Macro for generating end-to-end tests"
keywords.workspace = true
categories.workspace = true
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[lib]
proc-macro = true

[dependencies]
darling = { workspace = true }
# todo check greyed out deps
ink_ir = { workspace = true, default-features = true }
derive_more = { workspace = true, features = ["from"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
serde_json = { workspace = true }
syn = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
ink = { path = "../../ink" }
ink_e2e = { path = "../", features = ["sandbox"] }
temp-env = "0.3.6"

[features]
std = ["derive_more/std"]
sandbox = []
