[package]
name = "ink_e2e_macro"
version = "4.2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/paritytech/ink"
documentation = "https://docs.rs/ink_macro/"
homepage = "https://www.parity.io/"
description = "[ink!] Macro for generating end-to-end tests"
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[lib]
name = "ink_e2e_macro"
proc-macro = true

[dependencies]
ink_ir = { version = "4.2.0", path = "../../ink/ir" }
cargo_metadata = "0.15.3"
# todo: update to 3.0.0 once released
contract-build = { git = "https://github.com/paritytech/cargo-contract", branch = "v3.0.0" }
derive_more = "0.99.17"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
serde_json = "1.0.89"
syn = "2"
proc-macro2 = "1"
quote = "1"
which = "4.4.0"
