[package]
name = "delegator"
version = "4.0.0-alpha.2"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
publish = false

[dependencies]
ink = { path = "../../crates/ink", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }

adder = { path = "adder", default-features = false, features = ["ink-as-dependency"] }
subber = { path = "subber", default-features = false, features = ["ink-as-dependency"] }
accumulator = { path = "accumulator", default-features = false, features = ["ink-as-dependency"] }

[lib]
name = "delegator"
path = "lib.rs"
crate-type = ["cdylib"]

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",

    "adder/std",
    "subber/std",
    "accumulator/std",
]
ink-as-dependency = []

[workspace]
members = [
    "accumulator",
    "adder",
    "subber",
]
