[package]
name = "delegator"
version = "3.0.0-rc9"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
ink_primitives = { version = "3.0.0-rc9", path = "../../crates/primitives", default-features = false }
ink_metadata = { version = "3.0.0-rc9", path = "../../crates/metadata", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0-rc9", path = "../../crates/env", default-features = false }
ink_storage = { version = "3.0.0-rc9", path = "../../crates/storage", default-features = false }
ink_lang = { version = "3.0.0-rc9", path = "../../crates/lang", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }

adder = { version = "3.0.0-rc9", path = "adder", default-features = false }
subber = { version = "3.0.0-rc9", path = "subber", default-features = false }
accumulator = { version = "3.0.0-rc9", path = "accumulator", default-features = false }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }

[lib]
name = "delegator"
path = "lib.rs"
crate-type = ["cdylib"]

[features]
default = ["std"]
std = [
    "ink_primitives/std",
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_lang/std",
    "scale/std",
    "scale-info/std",

    "adder/std",
    "subber/std",
    "accumulator/std",
]

[workspace]
members = [
    "accumulator",
    "adder",
    "subber",
]
