[package]
name = "multisig_plain"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
ink_primitives = { version = "3.0.0", path = "../../primitives", default-features = false }
ink_metadata = { version = "3.0.0", path = "../../metadata", default-features = false, features = ["derive"], optional = true }
ink_core = { version = "3.0.0", path = "../../core", default-features = false }
ink_lang = { version = "3.0.0", path = "../../lang", default-features = false }
ink_prelude = { version = "3.0.0", path = "../../prelude", default-features = false }

scale = { package = "parity-scale-codec", version = "1.3", default-features = false, features = ["derive"] }
scale-info = { git = "https://github.com/paritytech/scale-info", branch = "aj-pub-types", default-features = false, features = ["derive"], optional = true }


[lib]
name = "multisig_plain"
path = "lib.rs"
crate-type = ["cdylib"]

[features]
default = ["std"]
std = [
    "ink_metadata",
    "ink_metadata/std",
    "ink_core/std",
    "ink_lang/std",
    "ink_primitives/std",
    "ink_prelude/std",
    "scale/std",
    "scale-info",
    "scale-info/std",
]
ink-as-dependency = []
